### ISSUE TITLE
Nested Calldata to Decode in Sponsored Safe Tx

### ISSUE THREAD

**Issue by jamesmccomish** [3loop/loop-decoder#151]
Safe offer to sponsor some tx if you execute from the Safe UI. They relay the tx in a call `sponsoredCallV2` which contains `_target` the Safe that the tx is related to, and `_data` which is the `executeTransaction` method on the Safe. If these become more common it could be worth handling them in the dedicated Safe decoding functions, or just include some more possibilities in `decodeBytesRecursively`

Example return from decodeTransaction on 3loop:
```
	"methodCall": {
		"name": "sponsoredCallV2",
		"type": "function",
		"signature": "sponsoredCallV2(address,bytes,bytes32,bytes32,bytes32)",
		"params": [
			{ "name": "_target", "type": "address", "value": "0x023acc684DdD9fA68eE72D5CCb97856499cF54F4" },
			{
				"name": "_data",
				"type": "bytes",
				"value": "0x123456..."
			},
			{
				"name": "_correlationId",
				"type": "bytes32",
				"value": "0xf4786c8be249271017682316487799e436490a3fbb240e7aef3ac083409bbbc4"
			},
			{
				"name": "_r",
				"type": "bytes32",
				"value": "0x6f1d0353c3c9b9c7e7b991a8139bc127e44b70c47af2c2c5ab025c33fa37d26a"
			},
			{
				"name": "_vs",
				"type": "bytes32",
				"value": "0x33482b5f85ffe8ecd671a92ceefcde9f6a3b4b9df845ead25788a40e18a26dba"
			}
		]
	},
```
	

Adding the `_data` and `_target` options [here](https://github.com/3loop/loop-decoder/blob/b994dbc55983f4c49a922846bcc403aa3965b7f1/packages/transaction-decoder/src/decoding/calldata-decode.ts#L21) might get around it.

**Comment by anastasiarods** [comment]
@jamesmccomish Thanks for submitting the issue! Added these keys, should now work for most calldata with nested params
